@startuml B2BUA Forking
!includeurl https://raw.githubusercontent.com/RestComm/design/master/telestax-style.plantuml!0
autonumber

actor Alice
actor B2BUA
actor Proxy
actor Bob
actor Carol

Alice -> B2BUA : INVITE
B2BUA -> Alice : Trying
B2BUA -> Proxy : INVITE
Proxy -> Bob : INVITE
Proxy -> Carol : INVITE
Bob -> Proxy  : 180 Ringing (ToTag 12345)
Carol -> Proxy : 183 Session Progress (ToTag 54321)
Proxy -> B2BUA  : 180 Ringing (ToTag 12345)
Note right of B2BUA : Original Early Dialog 1 created\nOn Same CTX
Proxy -> B2BUA : 183 Session Progress (ToTag 54321)
Note right of B2BUA : Forked EarlyDialog 2 created\nOn Same CTX
B2BUA -> Alice : 180 Ringing (ToTag 12345)
Note left of B2BUA : Original Early Dialog 3 created\nOn Same STX
B2BUA -> Alice : 183 Session Progress (ToTag 54321)
Note left of B2BUA : Forked Early Dialog 4 created\nOn Same STX
Alice <--> Carol : 1 minute wait for Carol to answer
Carol -> Proxy : 200 OK (ToTag 54321)
Proxy -> B2BUA  : 200 OK (ToTag 54321)
B2BUA -> B2BUA : Forked Dialog 2 Confirmed 
Bob -> Proxy  : 200 OK (ToTag 12345)
Proxy -> B2BUA : 200 OK (ToTag 12345)
B2BUA -> B2BUA : Original Dialog 1 Confirmed 
B2BUA -> Alice : 200 OK (ToTag 54321)
Alice -> B2BUA : ACK (ToTag 54321)
B2BUA -> Proxy : ACK (ToTag 54321)
Proxy -> Carol : ACK (ToTag 54321)
Alice <--> Carol : Media RTP
B2BUA -> Alice : 200 OK (ToTag 12345)
Alice -> B2BUA : ACK (ToTag 12345)
B2BUA -> Proxy : ACK (ToTag 12345)
Proxy -> Bob : ACK (ToTag 12345)
Alice -> B2BUA : BYE (ToTag 12345)
B2BUA -> Proxy : BYE (ToTag 12345)
Proxy -> Bob : BYE (ToTag 12345)
Bob -> Proxy  : 200 OK (ToTag 12345)
Proxy -> B2BUA : 200 OK (ToTag 12345)
B2BUA -> Alice : 200 OK (ToTag 12345)
Alice -> B2BUA : BYE (ToTag 54321)
B2BUA -> Proxy : BYE (ToTag 54321)
Proxy -> Carol : BYE (ToTag 54321)
Carol -> Proxy  : 200 OK (ToTag 54321)
Proxy -> B2BUA : 200 OK (ToTag 54321)
B2BUA -> Alice : 200 OK (ToTag 54321)

@enduml