@startuml B2BUA Forking
!includeurl https://raw.githubusercontent.com/RestComm/design/master/telestax-style.plantuml!0
autonumber

actor Alice
actor B2BUA
actor Proxy
actor Bob
actor Carol

Alice -> B2BUA : INVITE 100 Rel
B2BUA -> Alice : Trying
B2BUA -> Proxy : INVITE 100 Rel
Proxy -> Bob : INVITE 100 Rel
Proxy -> Carol : INVITE 100 Rel
Bob -> Proxy  : 180 Ringing (ToTag 12345)
Carol -> Proxy : 183 Session Progress (ToTag 54321)
Proxy -> B2BUA  : 180 Ringing (ToTag 12345)
Note right of B2BUA : Early Original Dialog 1 created\nOn Same CTX
Proxy -> B2BUA : 183 Session Progress (ToTag 54321)
Note right of B2BUA : Forked Dialog 2 created\nOn Same CTX
B2BUA -> Alice : 180 Ringing (ToTag 12345)
Note left of B2BUA : Early Dialog 3 created\nOn Same STX
B2BUA -> Alice : 183 Session Progress (ToTag 54321)
Note left of B2BUA : Forked Dialog 4 created\nOn Same STX

group PRACK Handling
Alice -> B2BUA : PRACK (ToTag 12345)
Alice -> B2BUA : PRACK (ToTag 54321)
B2BUA -> Proxy : PRACK (ToTag 12345)
Bob -> Proxy : 200 OK (ToTag 12345)
Proxy -> B2BUA  : 200 OK (ToTag 12345)
B2BUA -> Alice : 200 OK (ToTag 12345)
B2BUA -> Proxy : PRACK (ToTag 54321)
Proxy -> Bob : PRACK (ToTag 12345)
Proxy -> Carol : PRACK (ToTag 54321)
Carol -> Proxy : 200 OK (ToTag 54321)
Proxy -> B2BUA  : 200 OK (ToTag 54321)
B2BUA -> Alice : 200 OK (ToTag 54321)
end group

group UPDATE Handling
Carol -> Proxy : UPDATE (ToTag 54321)
Proxy -> B2BUA  : UPDATE (ToTag 54321)
B2BUA -> Alice : UPDATE (ToTag 54321)
Alice -> B2BUA : 200 OK (ToTag 54321)
B2BUA -> Proxy : 200 OK (ToTag 54321)
Proxy -> Carol : 200 OK (ToTag 54321)
Alice -> B2BUA : UPDATE (ToTag 54321)
B2BUA -> Proxy : UPDATE (ToTag 54321)
Proxy -> Carol : UPDATE (ToTag 54321)
Carol -> Proxy : 200 OK (ToTag 54321)
Proxy -> B2BUA  : 200 OK (ToTag 54321)
B2BUA -> Alice : 200 OK (ToTag 54321)
end group

Alice <--> Carol : 1 minute wait for Carol to answer
Carol -> Proxy : 200 OK (ToTag 54321)
Proxy -> B2BUA  : 200 OK (ToTag 54321)
B2BUA -> B2BUA : Forked Dialog 2 Confirmed 
B2BUA -> Alice : 200 OK (ToTag 54321)
Alice -> B2BUA : ACK (ToTag 54321)
B2BUA -> Proxy : ACK (ToTag 54321)
Proxy -> Carol : ACK (ToTag 54321)
Alice <--> Carol : Media RTP
group CANCEL Handling
Alice -> B2BUA : CANCEL (ToTag 12345)
B2BUA -> Proxy : CANCEL (ToTag 12345)
Proxy -> Bob : CANCEL (ToTag 12345)
Bob -> Proxy  : 200 OK CANCEL (ToTag 12345)
Proxy -> B2BUA : 200 OK CANCEL (ToTag 12345)
B2BUA -> Alice : 200 OK CANCEL (ToTag 12345)
Bob -> Proxy  : 487 Request Terminated (ToTag 12345)
Proxy -> B2BUA : 487 Request Terminated (ToTag 12345)
B2BUA -> Alice : 487 Request Terminated (ToTag 12345)
Alice -> B2BUA : ACK (ToTag 12345)
B2BUA -> Proxy : ACK (ToTag 12345)
Proxy -> Bob : ACK (ToTag 12345)
end group
Alice <--> Carol : Call Completed
Alice -> B2BUA : BYE (ToTag 54321)
B2BUA -> Proxy : BYE (ToTag 54321)
Proxy -> Carol : BYE (ToTag 54321)
Carol -> Proxy  : 200 OK (ToTag 54321)
Proxy -> B2BUA : 200 OK (ToTag 54321)
B2BUA -> Alice : 200 OK (ToTag 54321)

@enduml