@startuml Netty Stream Oriented Transport Protocols Request Processing
!includeurl https://raw.githubusercontent.com/RestComm/design/master/telestax-style.plantuml!0

autonumber
actor UAC

UAC -> Socket : INVITE
group Netty EventLoop Thread
    alt message from network case
        Socket -> Channel : bytes
        Channel -> NettyStreamMessageDecoder : decode(ByteBuf)
        NettyStreamMessageDecoder -> NettyMessageParser : new
        NettyStreamMessageDecoder -> NettyMessageParser : parseBytes(ByteBuf) \n all SIP Messages \n from the ByteBuf
        NettyStreamMessageDecoder -> ChannelInboundHandler : consume all SIP Messages \n decoded by the Parser \n and pass them upstream
        ChannelInboundHandler -> NettyMessageHandler : channelRead(SIPMessage)
        NettyMessageHandler -> NettyStreamMessageProcessor : createMessageChannel
        NettyStreamMessageProcessor -> NettyStreamMessageChannel : new if not already existing
        NettyMessageHandler -> NettyMessageHandler : deal with RFC5626 keepalives

        NettyMessageHandler -> IncomingMessageProcessingTask : new
        NettyMessageHandler -> MessageProcessorExecutor : addTaskLast        
    else message self routing case
        SipTransactionImpl -> IncomingMessageProcessingTask : new
        NettyMessageHandler -> MessageProcessorExecutor : addTaskLast        
    end 
end
group MessageProcessorExecutor WorkerThread        
    MessageProcessorExecutor -> MessageProcessorExecutor : pull task from queue
    MessageProcessorExecutor -> IncomingMessageProcessingTask : execute
    
    IncomingMessageProcessingTask -> SIPEventInterceptor : beforeMessage(SIPMessage)
    IncomingMessageProcessingTask -> NettyStreamMessageChannel : processMessage(SIPMessage)
    NettyStreamMessageChannel -> NettyStreamMessageChannel : check message validity and RPort
    NettyStreamMessageChannel -> NettyStreamMessageProcessor : cache Message Channel    
    NettyStreamMessageChannel -> SIPTransactionStack : newSIPServerRequest
    SIPTransactionStack -> SIPMessageValve : loop through valves and \n call processRequest on them
    SIPTransactionStack -> SIPServerTransaction : new    
    SIPTransactionStack -> NISTSIPMessageFactoryImpl : newSIPServerRequest 
    NISTSIPMessageFactoryImpl -> DialogFilter : new
    SIPTransactionStack -> SIPServerTransaction : setRequestInterface(DialogFilter))     
    SIPTransactionStack -> NettyStreamMessageChannel : send 100 Trying \n (if INVITE already being processed)
    NettyStreamMessageChannel -> SIPServerTransaction : processRequest
    SIPServerTransaction -> SIPServerTransaction : update FSM state
    SIPServerTransaction -> SIPServerTransaction : send 100 Trying \n (if necessary)
    SIPServerTransaction -> SIPServerTransaction : If retransmission send last response    
    SIPServerTransaction -> DialogFilter : processRequest
    DialogFilter -> RequestEventExt : new
    DialogFilter -> SipProviderImpl : handleEvent
    SipProviderImpl -> EventWrapper : new
    SipProviderImpl -> EventScanner : deliverEvent(EventWrapper) \n if reentrant listener
    EventScanner -> SIPListener : processRequest        
    IncomingMessageProcessingTask -> SIPEventInterceptor : afterMessage(SIPMessage)
end
@enduml