@startuml Netty Datagram Oriented Transport Protocol Initialization Process
!includeurl https://raw.githubusercontent.com/RestComm/design/master/telestax-style.plantuml!0

autonumber

Application -> SIPFactory : createSipStack
SIPFactory -> SIPStackImpl : new
SIPStackImpl -> WorkerPool : new
SIPStackImpl -> WorkerPool : start(sipStack.threadPoolSize)
SIPStackImpl -> MessageProcessorExecutor : start(sipStack.threadPoolSize)
Application -> SIPStackImpl : createListeningPoint
SIPStackImpl -> NettyMessageProcessorFactory : createMessageProcessor
NettyMessageProcessorFactory -> NettyDatagramMessageProcessor : new
NettyDatagramMessageProcessor -> ePollEventGroup : new (sipStack.threadPoolSize) \n used for incoming messages
NettyDatagramMessageProcessor -> serverChannels : new ConcurrentHashMap(\nsipStack.threadPoolSize) \n used for outgoing messages
SIPStackImpl -> NettyDatagramMessageProcessor : start
NettyDatagramMessageProcessor -> Bootstrap : new with EpollDatagramChannel
NettyDatagramMessageProcessor -> NettyDatagramChannelInitializer : new
NettyDatagramChannelInitializer -> NettyDatagramMessageDecoder : new
NettyDatagramChannelInitializer -> NettyMessageHandler : new
NettyDatagramMessageProcessor -> serverChannels : loop through serverChannels \n and bind to socketAddress
@enduml